import git
import os
import requests
import shutil
from urllib.parse import urlparse

class GitTool:
    def __init__(self, workspace_dir="./workspace"):
        self.workspace_dir = os.path.abspath(workspace_dir)
        
    def clone_repo(self, repo_url: str):
        """Clones a remote GitHub repository."""
        if os.path.exists(self.workspace_dir):
            try:
                # Force delete read-only files (common Windows issue)
                def on_error(func, path, exc_info):
                    import stat
                    os.chmod(path, stat.S_IWRITE)
                    func(path)
                shutil.rmtree(self.workspace_dir, onerror=on_error)
            except Exception as e:
                print(f"⚠️ Warning: Could not clean workspace: {e}")

        print(f"⬇️ Cloning {repo_url}...")
        self.repo = git.Repo.clone_from(repo_url, self.workspace_dir)
        print(f"✅ Cloned to {self.workspace_dir}")
        return self.workspace_dir

    # Add inside GitTool class in src/tools/git_tool.py

    def get_issues(self, repo_full_name, token, label="reporover"):
        """Fetches open issues with a specific label."""
        url = f"https://api.github.com/repos/{repo_full_name}/issues"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }
        params = {
            "state": "open",
            "labels": label
        }
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            return response.json()
        return []

    def post_comment(self, repo_full_name, issue_number, token, body):
        """Posts a comment on an issue."""
        url = f"https://api.github.com/repos/{repo_full_name}/issues/{issue_number}/comments"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }
        data = {"body": body}
        requests.post(url, headers=headers, json=data)
    def configure_user(self):
        """Configures a bot user for git commits."""
        with self.repo.config_writer() as git_config:
            git_config.set_value('user', 'email', 'bot@reporover.ai')
            git_config.set_value('user', 'name', 'RepoRover Bot')

    def create_branch(self, branch_name="fix/reporover-patch"):
        """Creates and switches to a new branch."""
        current = self.repo.create_head(branch_name)
        current.checkout()
        print(f"🌿 Switched to branch: {branch_name}")

    def commit_changes(self, message="Auto-fix by RepoRover"):
        """Stages all changes and commits them."""
        # 1. Add all changes
        self.repo.git.add(A=True)
        
        # 2. Check if there is anything to commit
        if self.repo.is_dirty():
            self.repo.index.commit(message)
            print(f"✅ Committed changes: '{message}'")
            return True
        else:
            print("⚠️ No changes detected to commit.")
            return False
    def create_pull_request(self, repo_full_name, token, title, body):
        """Automatically opens a Pull Request on GitHub."""
        url = f"https://api.github.com/repos/{repo_full_name}/pulls"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }
        data = {
            "title": f"🤖 AI Fix: {title}",
            "body": f"This PR was automatically generated by RepoRover.\n\n### Task:\n{body}",
            "head": "fix/reporover-auto-patch",
            "base": "main"  # or 'master'
        }
        response = requests.post(url, json=data, headers=headers)
        if response.status_code == 201:
            print(f"🔗 Pull Request Created: {response.json()['html_url']}")
            return response.json()['html_url']
        else:
            print(f"⚠️ PR failed (might already exist): {response.text}")
            return None
    def push_changes(self, branch_name, token):
        """Pushes the branch to remote using the token for auth."""
        origin = self.repo.remote(name='origin')
        original_url = origin.url
        
        if "https://" in original_url:
            auth_url = original_url.replace("https://", f"https://{token}@")
            
            print(f"🚀 Pushing to GitHub ({branch_name})...")
            try:
                # CHANGED: Added force=True to overwrite old bot attempts
                self.repo.git.push(auth_url, branch_name, force=True) 
                print("🎉 SUCCESS: Changes pushed to GitHub!")
                print(f"🔗 Link: {original_url}/tree/{branch_name}")
            except Exception as e:
                print(f"❌ Push failed: {e}")